### ISSUE TITLE
Type Error occurred when creating object: ImaginationMedia\Correios\Model\ResourceModel\Cotacoes\Collection\Interceptor

### ISSUE THREAD

**Issue by r-martins** [magenteiro/firestore#2]
Oi Ricardo boa noite!

Estou finalizando a configuração da Loja Store Fire e encontrei o problema abaixo no módulo de correios. Poderia por favor direcionar como posso solucionar o problema?

![image](https://user-images.githubusercontent.com/191149/98487971-85bc5980-227a-11eb-853a-7dd5bb095674.png)

Type Error occurred when creating object: ImaginationMedia\Correios\Model\ResourceModel\Cotacoes\Collection\Interceptor, Argument 5 passed to ImaginationMedia\Correios\Model\ResourceModel\Cotacoes\Collection\Interceptor::__construct() must implement interface Magento\Framework\DB\Adapter\AdapterInterface or be null, string given, called in /var/www/html/m2lcbrasil/src/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 121 

Reportado por Sergio Morais

**Comment by renato-tasso** [comment]
Olá, estou me deparando com a mesma mensagem, podem compartilhar como foi resolvido?

**Comment by sergiomsa** [comment]
@renato-tasso, ainda não obtive resposta. Eu preciso resolve isto até neste final de semana. Não tenho ideia de como.

**Comment by LuizSantos1** [comment]
@renato-tasso e @sergiomsa 
Magento 2 é modular, se o problema é urgente, minha sugestão seria desabilitar esse módulo e instalar outro que faça essa função até que resolvam por aqui.

**Comment by r-martins** [comment]
Corrigi há pouco no repositorio do meu fork.
Acredito que dê pra atualizar apenas o submodulo com o comando `git submodule update --remote src/app/code/ImaginationMedia/Correios`.

**Comment by r-martins** [comment]
Corrigi há pouco no repositorio do meu fork.
Acredito que dê pra atualizar apenas o submodulo com o comando `git submodule update --remote src/app/code/ImaginationMedia/Correios`.
Depois farei a atualização da firestore em si.

**Comment by andremc420** [comment]
Estou tentando atualizar o módulo em minha loja (não é firestore, mas utiliza o ImaginationMedia/Correios), porém o problema permanece com a versão mais atual (1.2.6) baixada do https://bitbucket.org/r_martins/

Se eu trocar o di.xml por este aqui mais antigo-> [commit 85402e8](https://bitbucket.org/r_martins/correios/commits/85402e832fe971b0fe168692a2277432928e6a1e) aparece um erro diferente:

```
Argument 1 passed to Magento\Framework\View\Element\UiComponent\DataProvider\DataProvider::searchResultToOutput() must implement interface Magento\Framework\Api\Search\SearchResultInterface, instance of ImaginationMedia\Correios\Model\ResourceModel\Cotacoes\Collection\Interceptor given, called in [Magento]/vendor/magento/framework/View/Element/UiComponent/DataProvider/DataProvider.php on line 282
Exception in [Magento]/vendor/magento/framework/View/Element/UiComponent/DataProvider/DataProvider.php:243
```
Alguém conseguiu fazer o módulo funcionar?

Magento 2.4.3-p2, PHP 7.4.

**Comment by r-martins** [comment]
Obrigado por reportar, @andremc420 .
Atualizei o módulo. Pode tentar novamente com a versão 1.2.8 ?

**Comment by andremc420** [comment]
Oi Ricardo, testei agora. Os erros desapareceram, eu consigo popular o banco de dados, porém quando tento atualizar as faixas, ele demora alguns minutos e depois retorna "0 faixas de CEP atualizadas com sucesso e 106 com erro." 

Quando tento calcular o frete ou finalizar o pedido, a página trava com o gif de Carregando e um alerta de erro quebrado no campo do método de entrega -> [imagem](https://i.imgur.com/OUwGe7z.png).
O arquivo de log do módulo não foi criado, e não foi registrado erro nenhum no exception.log. 

EDIT: Agora funcionou, após desabilitar o módulo One Step Checkout da Amasty.

**Comment by r-martins** [comment]
Qual CEP da loja você tem configurado?
