### ISSUE TITLE
Problema ImaginationMedia Correios

### ISSUE THREAD

**Issue by gilliattbastos** [magenteiro/firestore#3]
Estou com problema quando tento colocar a loja em produção.

Repositories code generation... 1/9 [===>------------------------]  11% < 1 sec 81.0 MiBPHP Parse error:  syntax error, unexpected 'EavSetup' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /src/app/code/ImaginationMedia/Correios/Setup/UpgradeData.php on line 13

Se alguém tiver alguma dica. Agradeço a atenção.

**Comment by r-martins** [comment]
Verifique a versão do seu PHP.
Ela deve ser compatível com o Magento sendo instalado.
