### ISSUE TITLE
erro ao instalar componente do pagtesouro faltando no marketplace

### ISSUE THREAD

**Issue by CamiloSales** [magenteiro/firestore#7]
Ao instalar seguindo o passo do curso magenteiro recebi o seguinte erro:

  - Installing ricardomartins/pagseguro (2.9.7): Downloading (failed)
               In RemoteFilesystem.php line 438:
               The "https://repo.magento.com/archives/ricardomartins/pagseguro/ricardomartins-pagseguro-2.9.7.0.zip" file could not be downloaded (HTTP/1.1 404 Not Found)

**Comment by r-martins** [comment]
rode um `composer update` antes do install e deverá funcionar. ;)
