### ISSUE TITLE
erro ao instalar, arquivo pagseguro faltando

### ISSUE THREAD

**Issue by CamiloSales** [magenteiro/firestore#8]
ao realizar instalação seguindo passo do curso instalar firestore do site magenteiro, encontrei o seguinte erro: 

 - Installing ricardomartins/pagseguro (2.9.7): Downloading (failed) 
               In RemoteFilesystem.php line 438:
               The "https://repo.magento.com/archives/ricardomartins/pagseguro/ricardomartins-pagseguro-2.9.7.0.zip" file could not be downloaded (HTTP/1.1 404 Not Found)

**Comment by r-martins** [comment]
rode um composer update antes do install e deverá funcionar. ;)
